apiVersion: v1
kind: Service
metadata:
  name: ubuntu-desktop-lxde-vnc
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "ubuntu-desktop-lxde-vnc"
    port: 6080
  selector:
    app: ubuntu-desktop-lxde-vnc
